version: 1.0.{build}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
install:
- cmd: git submodule update --init --recursive
build:
  project: eazdevirt.sln
  verbosity: detailed
artifacts:
- path: bin\$(configuration)
  name: eazdevirt-Release
  type: zip
